### PR TITLE
Create Bangazon_TaskTracker

### PR DESCRIPTION
**Pull request by copypastedeveloper**
@stevebrownlee, This is what I'm thinking of kicking them off on.  Thoughts?

### CODE REVIEW

**Comment by stevebrownlee** [comment]
Can you submit this pull request on the https://github.com/nashville-software-school/alumni-enrichment-program repo instead?

**Comment by stevebrownlee** [comment]
I think it's a great project to start on as a pair programming exercise.

**Comment by stevebrownlee** [comment]
Just go ahead and leave this PR open as well.  If the project works well for your team, I'll add it for the next day cohort

**Comment by stevebrownlee** [comment]
Dang, just missed it  :)

**Comment by ncgonz** [comment]
its a race.

**Pull request closed without merging**
