### PR TITLE
Music history sql server

### LINKED ISSUE #65: Change music history exercise to use SQL Server

### PR DESCRIPTION
**Pull request by askingalot**
Resolves #65

### CODE REVIEW

**Comment by copypastedeveloper** [comment]
This is pretty similar data to whats in Chinook.  is this reused in a later exercise and that's why its being used here?

**Comment by askingalot** [comment]
I’m not sure I understand. This is the intro to sql chapter. It’s the same as it was before. It’s just not in sqlite any more. 

Are you suggesting we don’t need this and chinook?

**Comment by copypastedeveloper** [comment]
I guess I never used this exercise because it was in sqlite, so i'm not familiar with the data.  I was mainly just saying that since they have to create chinook, and this data is suspiciously similar in structure to some of the chinook tables, why not just use chinook.  no big deal either way.

**Comment by stevebrownlee** [comment]
@copypastedeveloper Because employers keep demanding more SQL knowledge, I split the exercises to work on raw SQL out into three distinct parts of the course. This implements the strategies of spacing and interleaving to strengthen their understanding.

1. Orientation has a small intro to SQL with Music History
1. Between sprints 1 and 2, a larger set of exercises with Chinook
1. Between sprints 3 and 4, another large set of exercises with Northwind

**Pull request merged**
