### PR TITLE
updates to the test chapter

### PR DESCRIPTION
**Pull request by askingalot**
We're now testing controllers using a mock repository.

### CODE REVIEW

**Review by copypastedeveloper — CHANGES_REQUESTED** [review]
I know there are differing opinions on this, but here's mine: testing controllers like this seems like a useless example of something I'd never want an employee to do.  In the end with the second implementation you've written what you're actually testing is a different implementation.  You could break the test by changing the test implementation while the actual code still works fine.

Why not teach unit testing with something more logical and use branching, and then you can avoid mocking. We use the bowling score calculator kata, or the Josephus problem as testing examples.

**Comment by askingalot** [comment]
You have a good point. As I got into it, I realized that some of what I'm testing is the code in the mocked repository. In a production app with reasonably thin controllers, I might not test controllers at all. If I were to test a controller, I'd certainly use something like Moq to build a repository stub instead of writing a custom in-memory repo. I'd use the features of Moq that verify a particular method was called more heavily than verifying the repo returned the data I expected. I debated teaching Moq, but decided that's more than the students are ready to internalize.

That being said, I think what I've done meets my objectives. It introduces unit testing, illustrates (some of) the value of coding against an interface, is, at least, similar to what is done in the real world, and, most importantly, is yet another opportunity for the students to practice reading and interpreting code.

In general I'm against teaching students bad habits, but I'm not particularly concerned about it in this case. We spend so little time with testing that I can't imagine any student is going to internalize the whole of the code. Frankly, I don't think anyone will understand it well enough to be injured by it.

**Comment by askingalot** [comment]
On a related note, it's on my long-term todo list to experiment with introducing unit testing (and perhaps TDD) during orientation. I think the bowling kata would be a great fit if we did that. 

Also, I'd completely forgotten about the Jsephus problem. I had to look it up before I realized it was something I ~am~ used to be familiar with.

**Comment by copypastedeveloper** [comment]
For the record I think the fact that students can't internalize the code you've written here is exactly the reason you shouldn't be showing it to them this way.  Unit testing is a simple concept, and if you present it with some simple branching, logic based code its easy and quick to grasp.  I just taught it this week.  We spent 3 hours on it including lecture on background, and wrote around 100 lines of code in total, only ~ 10 of which were real code.  They have exercises to work on with it like roman numeral conversion and the bowling game to get repetition.  In the end the test are realistic and useful.

here's a [link to the code along ](https://github.com/nss-evening-cohort-11/Josephus), and the notes I drew during lecture.
testing

**Comment by stevebrownlee** [comment]
I've discussed this with Andy in person, and Nathan has shared his opinions with me. Here's my take on this issue.

1. We need to show students the mechanism of testing code. It's one of our core course learning objectives.
1. The mechanism by which we expose them to it is of less importance. Let's remember that mastery of the concept is not the objective, just knowledge and understanding.
1. Context is extremely important for beginners. Therefore, showing them testing in the context of a project should take precendence.
1. We have no way of knowing what kind of testing they will **actually** experience, so we can't show them all the ways.

Therefore, I would prefer that your course show them testing within the context of a project they are actively developing (e.g. Tabloid or Bangazon) rather than isolated, small one-off projects. However, both ways effectively introduce students to the skill of testing and gets them the knowledge and understanding they need during their time at NSS.

So you're both right in the context of NSS learning objectives.

Let's always remember that students forgot the fine-grain details of many things that we teach, and that we should be far more concerned with their ability to learn, research, and apply concepts in many different contexts instead of focusing on a single context ourselves.

**Pull request merged**
