### PR TITLE
ssms intro

### LINKED ISSUE #63: Add SSMS Chapter to Orientation

### PR DESCRIPTION
**Pull request by askingalot**
Resolves #63

### CODE REVIEW

**Comment by copypastedeveloper** [comment]
I think this is a good start.  I wonder if we should include keyboard shortcuts, and maybe something with the toolbars and what the buttons mean.  A lot of it is not intuitive at all.  Also, thinking towards the future I wonder if we can/should move to azure data studio.

**Comment by askingalot** [comment]
I threw the tutorial link into the bottom of the article because it goes into more detail. It covers some of the buttons and also has pictures. Frankly I was hoping to outsource to that article a little. Should We make going through that tutorial a mandatory exercise?

Is azure data studio the future? When do you think MS is going to start pushing it over SSMS?

**Comment by copypastedeveloper** [comment]
I think outsourcing to the article is fine.  Missed that it was there. 

> Is azure data studio the future? When do you think MS is going to start pushing it over SSMS?
I think it has to be, when was the last time ssms got a meaningful update?  meanwhile data studio gets a new release almost monthly now.  Other than some of the gui stuff like table designers it already works pretty close to as well as ssms for standard workloads.  AND IT SAVES YOUR TABS WITHOUT YOU HAVING TO SAVE THEM!!!!  :)  I'm fine with SSMS, and that's what we're covering, just wanted to toss the alternative out there for thinking about in the next year.

**Comment by askingalot** [comment]
SSMS hasn't changed much since they switched it to use a VS shell (2010?)...and even then it didn't change so much from what it had been previously. I'd be excited to have a more modern and user friendly alternative.

**Pull request merged**
